apiVersion: apps/v1
kind: Deployment
metadata:
  name: humix-api-gateway
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: humix-api-gateway
  template:
    metadata:
      labels:
        app: humix-api-gateway
    spec:
      containers:
      - name: humix-api-gateway
        image: imagem
        ports:
        - containerPort: 8080
