apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gateway

images:
- name: imagem
  newName: blgianini/canal-deploy
  newTag: b34f4586fedcc0c9212e8a8bea74d3a69c9e93e1
