apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: gateway

images:
- name: imagem
  newName: blgianini/humix
  newTag: 526cba95797d598bc5c78fde3172647383841e01
